global_costmap:
  global_frame: "2d_map"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  static_map: true

local_costmap:
  global_frame: "2d_map"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  static_map: false
  rolling_window: true

base_global_planner: "navfn/NavfnROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
